name: Build QoS Module

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Android NDK
        run: echo "ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake

      - name: Make Script Executable
        run: chmod +x scripts/build.py

      - name: Compile Daemon
        if: github.ref_type != 'tag'
        run: python scripts/build.py --target daemon --type Release

      - name: Full Build and Package Module
        if: github.ref_type == 'tag'
        run: python scripts/build.py --target module --type Release

      - name: Upload Magisk Module Artifact
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: qos-magisk-module
          path: scripts/output/*.zip
          retention-days: 1
